name: Repo Checkout Action
description: "Checkout repo"

inputs:
  fetchdepth:
    required: false
    type: number
    default: 1
    
runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: ${{ inputs.fetchdepth }}