name: Golang Setup
description: "Setups up Golang versions"

inputs:
  golang_version:
    required: false
    description: "Golang version to use"
    default: "1.18.9"


runs:
  using: "composite"
  steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go version
        uses: actions/setup-go@v3.3.1
        with:
          go-version: ${{ inputs.golang_version }}

      - name: Check the Go version
        run: go version
        shell: bash