name: Golang Setup
description: "Setups up Golang versions"

inputs:
  golang_version:
    required: false
    type: string
    default: "1.18.9"


runs:
  using: "composite"
  steps:
      - name: Setup Go version
        uses: actions/setup-go@v3.3.1
        with:
          go-version: ${{ inputs.golang_version }}
      - run: go version