name: Docker Lint

on:
  workflow_call:
    inputs:
      docker-file:
        required: true
        type: string
        default: "Dockerfile"

jobs:
  lint:
    name: Docker Lint
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0
      
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: ${{ inputs.docker-file }}