---

name: Example CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Step
    uses: ./.github/workflows/lint.yml

  test:
    name: Test Step
    uses: ./.github/workflows/test.yml

  build:
    name: Build Step
    uses: ./.github/workflows/build.yml

  scan:
    name: Scan Step
    uses: ./.github/workflows/scan.yml

  deploy:
    name: Deploy Step
    uses: ./.github/workflows/deploy.yml