name: Golang Scan

on:
  workflow_call:

jobs:
  checkout:
    name: Checkout
    uses: ./.github/workflows/checkout.yml

  setupgo: 
    name: Setup Go version
    uses: ./.github/workflows/go_application_setup.yml

  audit:
    name: Golang Scan
    needs: [checkout, setupgo]
    runs-on: ubuntu-20.04
    env:
      GO111MODULE: on
    steps:

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...

      - name: Create Go dep list
        run: go list -json -m all > go.list

      - name: Scan application with Nancy
        uses: sonatype-nexus-community/nancy-github-action@v1.0.2
        with:
          nancyVersion: "v1.0.42"
          goListFile: go.list