name: Golang Lint

on:
  workflow_call:

jobs:
  checkout:
    name: Checkout
    uses: ./.github/workflows/checkout.yml

  setupgo: 
    name: Setup Go version
    uses: ./.github/workflows/go_application_setup.yml

  lint:
    name: Golang Lint
    runs-on: ubuntu-20.04
    steps:
    
      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          distribution: goreleaser
          version: v1.12.3
          install-only: true
      
      - name: Run goreleaser check
        run: goreleaser check

      - name: Run Go linting
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: "v1.50.1"