name: Golang Test

on:
  workflow_call:

jobs:
  checkout:
    name: Checkout
    uses: ./.github/workflows/checkout.yml

  setupgo: 
    name: Setup Go version
    uses: ./.github/workflows/go_application_setup.yml

  test:
    name: Golang Test
    runs-on: ubuntu-20.04
    steps:

       - name: Verify dependencies
         run: go mod verify

       - name: Run Go test
         run: go test -v

       - name: Check coverage
         run: go test -cover