name: Golang Test

on:
  workflow_call:

jobs:
  test:
    name: Golang Test
    runs-on: ubuntu-20.04
    steps:

       - name: Checkout 
         uses: actions/checkout@v3.1.0

       - name: Setup Go version
         uses: crushten/github_workflow_repo/.github/workflows/go_application_setup.yml@main

       - name: Verify dependencies
         run: go mod verify

       - name: Run Go test
         run: go test -v

       - name: Check coverage
         run: go test -cover