name: Golang Test

on:
  workflow_call:

jobs:
  test:
    name: Golang Test
    runs-on: ubuntu-20.04
    steps:

       - name: Use local action checkout
         uses: ./.github/actions/checkout.yml

       - name: Use local action Golang setup
         uses: ./.github/actions/go_application_setup.yml

       - name: Verify dependencies
         run: go mod verify

       - name: Run Go test
         run: go test -v

       - name: Check coverage
         run: go test -cover