name: Golang Release

on:
  workflow_call:
    inputs:
      registry-url:
        required: false
        type: string
        default: "ghcr.io"
      image-name:
        required: false
        type: string
        default: ${{ github.repository }}
      application_directory:
        required: false
        type: string
        default: "."

jobs:
  checkout:
    name: Checkout
    uses: ./.github/workflows/checkout.yml
    with:
      fetchdepth: 0

  setupgo: 
    name: Setup Go version
    uses: ./.github/workflows/go_application_setup.yml

  release:
    name: Release
    needs: [checkout, setupgo]
    runs-on: ubuntu-20.04
    steps:

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Install syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.54.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          distribution: goreleaser
          version: v1.12.3
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}