name: Golang Lint

on:
  workflow_call:

jobs:
  lint:
    name: Golang Lint
    runs-on: ubuntu-20.04
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Go version
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: 'go.mod'
      - run: go version

      - name: Run Go linting
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: "v1.50.1"

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          distribution: goreleaser
          version: v1.12.3
          install-only: true
      
      - name: Run goreleaser check
        run: goreleaser check