name: Golang Lint

on:
  workflow_call:

jobs:
  lint:
    name: Golang Lint
    runs-on: ubuntu-20.04
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use local action Golang setup
        uses: crushten/github_workflow_repo/.github/actions/go_app_setup@main

      - name: Install goreleaser
        uses: goreleaser/goreleaser-action@v3.2.0
        with:
          distribution: goreleaser
          version: v1.12.3
          install-only: true
      
      - name: Run goreleaser check
        run: goreleaser check

      - name: Run Go linting
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: "v1.50.1"