name: Terraform Lint

on:
  workflow_call:
    inputs:
      terraform_directory:
        required: false
        type: string
        default: "."

jobs:
   terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3.1.0
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.4
          terraform_wrapper: false

      - name: Terraform fmt
        uses: dflook/terraform-fmt-check@v1.29.0
        id: terraform-lint-fmt-check
        with:
          path: ${{ inputs.terraform_directory }}

      - name: Wrong formatting found
        if: ${{ failure() && steps.terraform-lint-fmt-check.outputs.failure-reason == 'check-failed' }}
        run: echo "terraform formatting check failed"

      - name: Terraform init
        id: terraform-lint-init
        run: terraform init -input=false

      - name: Terraform validate
        uses: dflook/terraform-validate@v1.29.0
        id: terraform-lint-validate
        with:
          path: ${{ inputs.terraform_directory }}

      - name: Validate failed
        if: ${{ failure() && steps.terraform-lint-validate.outputs.failure-reason == 'validate-failed' }}
        run: echo "terraform validate failed"

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v2.0.1
        with:
          tflint_version: v0.42.2

      - name: Show tflint version
        run: tflint --version

      - name: Init tflint
        run: tflint --init

      - name: Run tflint
        run: tflint