name: Terraform Test

on:
  workflow_call:

jobs:
  terraform-test:
    name: Terraform Test
    needs: terraform-lint
    runs-on: ubuntu-20.04
    steps:

       - name: Checkout 
         uses: actions/checkout@v3.1.0

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2.0.3
         with:
           terraform_version: 1.3.4
           terraform_wrapper: false

       - name: Terraform init
         run: terraform init -input=false

       #- name: Terraform Plan
         #run: cd terraform/ && terraform plan -no-color